#!/usr/bin/env python
# Build: scons platform=windows target=template_release
# Needs: godot-cpp checked out next to this file (see README.md), MSVC, SCons.
import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

# COM / WASAPI for the audio peak meter.
env.Append(LIBS=["Ole32", "User32"])

library = env.SharedLibrary(
    "../bin/win64/deskcat_native{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
